#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/happ-decoder

start_service() {
    config_load 'happ-decoder'

    local enabled port
    config_get_bool enabled 'main' 'enabled' 0
    config_get port 'main' 'port' '8080'

    [ "$enabled" -eq 1 ] || return 0

    procd_open_instance
    procd_set_param command "$PROG" -port "$port"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    procd_send_signal happ-decoder
}

service_triggers() {
    procd_add_reload_trigger "happ-decoder"
}
